version: '3'

services:
  redis:
    container_name: redis
    image: redis:alpine3.8
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - './data/redis:/data'
    restart: always
    hostname: redis
    # command: redis-cli config set stop-writes-on-bgsave-error no && redis-server
  db:
    image: postgres:10
    container_name: django_db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
